### ISSUE TITLE
Daily Auto-Export to CSV

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#15]
TM should back up its database contents to a CSV file. I had previously thought this should happen on a daily basis but now I'm not so sure. Potentially this could be added to the MAINTENANCE interface, so that if we make breaking changes as part of development we can be sure to back up our dev-life to a file.  I AM sure that the file created should contain one days work. Thanks.

**Comment by Capm96** [comment]
@ancbro I see you assigned this to yourself -- if you are busy with other things, I'd be happy to give it a try :) let me know

**Comment by Capm96** [comment]
> @ancbro I see you assigned this to yourself -- if you are busy with other things, I'd be happy to give it a try :) let me know

nvm! Just saw the to-do page and saw that this is in progress for you, my bad.

**Comment by ancbro** [comment]
I clearly am lazy and have not finished. I will take my name off this. I still want the Slack one though. Lol.

**Comment by Capm96** [comment]
Could I take this one? I have played around with exporting to CSV in C# before, and would like to learn how to do it in Python.

**Comment by ancbro** [comment]
This ticket will resurface in a somewhat different from. I'm sort of rethinking how to create and distribute issues for this project. Thanks.
