### ISSUE TITLE
Increase Test Coverage

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#21]
`unittest` was introduced much too late in this project. Please place modules under test where they are not currently.

**Comment by Capm96** [comment]
@ancbro I can take a look at this one, pretty sure we can add some more tests around the database methods at the very least. I wonder how we can unit test the main methods though (like creating a note)? Not so familiar with how to do it in python. I guess that's more of an integration test?

**Comment by ancbro** [comment]
Yeah I wouldn't worry too much about all the side effecting code. I did push a change to the `DatabaseFacade`, so that when you call the constructor without a table name it will create an in memory database, which allows us to deterministically provision that database and then execute tests against it. 

`def __init__(self, name=":memory:"):`

So even if we add a couple more tests I would feel fine closing this ticket. It's more of a reminder for me than anything, and a good starting point of someone wanted to learn about `unittest` or something.

**Comment by Capm96** [comment]
Nice! Let me add a few more tests using facady.py and we can close this ticket if you'd like.
