### ISSUE TITLE
Define API for Slack Integration

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#25]
Integrate Time Management (TM) with Slack.

**Is your feature request related to a problem? Please describe.**
There's usually a Tech Lead, Boss, or Project Manager interested in your Sprint progress. TM is a great way to share that progress.

**Describe the solution you'd like**
Any fundamental IO should be available for viewing via Slack. Please enable a menu option or automated solution for publishing TM to Slack.

**Comment by anilchoudary** [comment]
I am very much interested to contribute. Can I work on this project ?

**Comment by ancbro** [comment]
@anilchoudary If you are interested in this issue specifically I can assign it to you; or if you are interested in other aspects of the project let me know and we can come up with something. Thanks!

**Comment by Ching9495** [comment]
Hi, I am a novice, I am very interested in your project, may I join?

**Comment by ancbro** [comment]
> Hi, I am a novice, I am very interested in your project, may I join?

@Ching9495; apologies. Tickets have been a little thin lately, but I will attempt to fix that. You are very welcome to pick up any you feel comfortable with. If there is something specific you would like to tackle I can cook up a task.

Best, Andrew

**Comment by tphan9** [comment]
@ancbro Hi, I'm a beginner and would like to contribute to this project. Are there any coding contributions I could make?

**Comment by ancbro** [comment]
@tphan9 I will make some more tickets this weekend for people to work on. Thanks for your interest!

**Comment by tphan9** [comment]
Hey @ancbro , can you tell me more about what you have in mind for the Slack Integration? What features do you want? How do you want for TM to function within Slack?

**Comment by ancbro** [comment]
> Hey @ancbro , can you tell me more about what you have in mind for the Slack Integration? What features do you want? How do you want for TM to function within Slack?

Hey @tphan9. Good question. Give me a little while and I will update the acceptance criteria to be more specific. Thanks.

**Comment by ancbro** [comment]
Closing this issue to create smaller tickets to better handle the scope of the feature.
