### ISSUE TITLE
SCRUM Banner Printing Too Close To List Items

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#27]
**Describe the bug**
When selecting the option to print SCRUM notes, and assuming there are any to be printed from the previous day, the application:

1. Prints the SCRUM banner
2. Begins printing the SCRUM notes on the line **immediately** below the banner, rather than providing a newline between the banner and the notes.

This is not a functional issue but it doesn't look nice either. It also reveals a number of poor practices that I have employed thus far, including:

1. The parsing and printing of a banner is tightly coupled to the number of newlines in the banner text file
2. A user cannot easily recreate the issue if they do not have SCRUM notes to print (notes from the previous day)
3. This functionality is not under test

**To Reproduce**
1. Issue `python3 main.py` OR `make run` for *nix* users to start the program
2. Select option 1 for **Time Management**
3. Select option 6 for **Print SCRUM Notes**
4. See poorly formatted output

**Expected behavior**
Ideally, each banner printed to the console should have a consistent amount of breathing space below it. The number of newlines to be displayed should be determined by the functions given below which can be found in 
**time-management/interface_common.py**. Naturally, additional functions can be employed if desired.

```
def parse_ascii_banner(file):
    f = open(file, "r")
    lines = f.readlines()
    f.close()
    return lines

def print_ascii_banner(lines):
    for line in lines:
        print(line.rstrip("\n"))

def clear_screen():
    if name == "nt":
        _ = system("cls")
    else:
        _ = system("clear")
```

**Screenshots (redacted)**
![image](https://user-images.githubusercontent.com/42525414/89356805-47643c80-d684-11ea-859c-fd185bdc5761.png)

**Comment by Straywind** [comment]
Where exactly? As far as I can tell printing notes and printing the SCRUM banner occur separately. The banner and the notes never seem to print at the same time. Or am I missing something obvious?

**Comment by ancbro** [comment]
@Straywind Sorry for the hastily written and vague ticket. Sometimes I just need to jot down an issue and move on with my day. I should learn not to do that in a ticket, but rather just use the program instead. I have updated the description of the bug, but that of course does not mean it is perfectly explained. Please don't hesitate to let me know if you have further questions. Best, ancbro.

**Comment by Straywind** [comment]
@ancbro No worries. I tried yesterday to recreate the problem, but couldn't find where. I'll have another go and see if I can't fix it.

**Comment by Straywind** [comment]
@ancbro Hum, seems to be better, but that is for you to decide.
I had to comment out part of a line in kronos.py to recreate the issue:
 yesterday = today - #timedelta(days=1)

At the least it now prints a line after the SCRUM banner.

**Comment by Straywind** [comment]
I sent a pull request and then another to fix up a small bug created by my first pull, so you can review those when you are ready.
