### ISSUE TITLE
get_all_items Should Not Impose Format On Query

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#38]
**Describe the bug**
The function **get_all_items** should return only the raw value of the query. Formatting the value for sending to stdout makes it difficult to re-use the function if you only want the core value of some queried field.

**To Reproduce**
1. Call **get_all_items** and notice that fields returned from individual rows like _date_ don't just return the date, but a header for that field.

Example code to reproduce:
```
items = facade.get_all_items()
        for item in items:
            if item is not None:
                row = item.split(",")
                print(row[1])
```

**Expected behavior**
The above code should only return a raw value from a field. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42525414/89742110-a3e8a280-da5c-11ea-9e6b-14c502a199bf.png)

**Comment by Straywind** [comment]
I'll look at this while I wait for you to decide on my current pull request

**Comment by Straywind** [comment]
Hmm, would it be the same issue with get__overdue_items, or do you not mind if that self formats? I feel that for consistency both should be adjusted.
