### ISSUE TITLE
SCRUM reports from Monday Print Reports From All Previous Fridays

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#40]
**Describe the bug**
SCRUM reports from Monday will print reports from all Fridays.

**To Reproduce**
To be given if necessary. See ` def get_last_days_items(self):`

**Expected behavior**
Monday should print last Friday's SCRUM reports but not Friday's from before then. 

**Screenshots**
To be given if necessary.

**Comment by angiesk** [comment]
Hi is anyone working on this currently ?

**Comment by ancbro** [comment]
Nope. You are more than welcome to it. Apologies for the poorly documented ticket and lack of tests. I can follow up tomorrow if there are questions.

**Comment by Straywind** [comment]
@angiesk You'll find the problem in facade.py in the get_last_days_items function

**Comment by ancbro** [comment]
@angiesk I assigned this to you. If you decide you do not want to tackle this issue then let me know. Either way is totally fine. Thanks so much for your interest!

**Comment by AyushRawal** [comment]
Hi! Is anybody working on this issue?

**Comment by AyushRawal** [comment]
Hi! Is anyone working on this? If not, please assign it to me.

**Comment by AyushRawal** [comment]
I have solved this issue and issued a PR. Please check it out.
Sorry for not getting assigned first.

**Comment by ancbro** [comment]
Thanks @AyushRawal I will assign you to the issue and get the review done. @angiesk Hope that's OK. Let me know if there is anything else you are interested in picking up instead.
