### ISSUE TITLE
Define Table Schemas

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#48]
Please finalize a schema for Notes and Tasks tables in the time_management database. 

In order to create new tickets for people to work on, we should have a common understanding of the schema our tables will be conforming to. 

Schemas can be found at _time_management/table_schemas_, and currently reflect the following:

Notes:
```
{
    "id": "int",
    "type": "text",
    "date": "text",
    "note": "text"
}
```

Tasks:
```
{
    "id": "int",
    "type": "text",
    "date": "text",
    "task": "text",
    "complete_in_days": "text",
    "is_complete": "text"
}
```

**Comment by ancbro** [comment]
@Straywind @Capm96 I figured I would ask you both if you're comfortable with the schemas I created above. That way I can create new tickets for people to work on and they aren't blocked by not knowing what the database is going to look like. Thanks.

**Comment by Straywind** [comment]
Looks fine to me.

**Comment by Capm96** [comment]
Looks good to me too
