### ISSUE TITLE
Separate Notes and Tasks 

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#54]
**Is your feature request related to a problem? Please describe.**
As users have noted, it's chaotic to see notes and tasks interleaved when printed to the interface. Please create two SQLite tables, one for notes and one for tasks. Then allow users the ability to print their notes or tasks separately. You may choose to keep or remove or modify the ability to print both at the same time as you see fit. 

**Describe the solution you'd like**
The following JSON schemas have been or will be provided (one update needs to be made to the master branch to include the is_void column). Please use them as part of the DML/DDL for create the tables. I.e., read the JSON from the files as part of the code to create and update the tables. These configuration files will make it easier to provide a framework for producing new tables, as well as modifying existing ones. 

Notes:
```
{
    "id": "int",
    "type": "text",
    "date": "text",
    "note": "text"
}
```
Tasks:
```
{
    "id": "int",
    "type": "text",
    "date": "text",
    "task": "text",
    "complete_in_days": "text",
    "is_complete": "text",
    "is_void": "text"
}
```

**Comment by ancbro** [comment]
@Capm96 Since you brought this issue to the fore-front (thanks) I was going to assign to you. If you would prefer not to work on it, let me know and I will remove the assignment. Thanks as always.

**Comment by Capm96** [comment]
No problem at all, happy to work on this.

**Comment by Straywind** [comment]
So... is there progress on this, or do you need a hand?

**Comment by Capm96** [comment]
Sorry @Straywind and @ancbro , been a bit busy this week, and think will still be going on the next one. If this can wait I am happy to take this later on, otherwise feel free to assign it to someone else. My apologies

**Comment by Straywind** [comment]
Just thought I'd offer a hand. I'll let ancbro decide.

**Comment by ancbro** [comment]
> Sorry @Straywind and @ancbro , been a bit busy this week, and think will still be going on the next one. If this can wait I am happy to take this later on, otherwise feel free to assign it to someone else. My apologies

No need to apologize. There is (obviously) no timeline, no obligation, and it's all just for fun. I have some PTO coming up at the end of this week and into the next, so I'm hoping to be able to tackle a few issues and make some more tickets. If at that time we think it would make sense to break this issue into smaller tickets, I will certainly do so. 

Peace.

**Comment by ancbro** [comment]
@Capm96 I added an additional field to the tasks table. I figure this will be useful for the analytics interface in allowing us to derive metrics surrounding how long it takes on average to complete a task. Thanks as always for your patience and contributions. Best, Andrew.
```
{
    "id": "int",
    "type": "text",
    "date_set": "text",
    "task": "text",
    "complete_in_days": "text",
    "date_complete": "text",
    "is_complete": "text",
    "is_void": "text"
}
```

**Comment by ancbro** [comment]
I am starting to lay the groundwork for how this should be accomplished. As such I am going to close this ticket, which is very broad, and create a number of smaller issues. Stay tuned.
