### ISSUE TITLE
Unable to add README to table_schemas directory

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#64]
We would like to add a README to `time_management/table_schemas`, to explain the purpose of the directory and the requirements for adding a new table to the program . However, any file in this directory is parsed with the expectation of being a JSON file, and non-JSON files added to the directory will crash the program. Please modify the code to handle other types of file extensions; which is to say, any non JSON file should simply be ignored in this folder.

**To Reproduce**
1. Add a non-JSON file to  `time_management/table_schemas`.
2. Start the program. 
3. Note the stack trace that occurs:
`/time-management/time_management/ddl.py", line 40, in parse_json
    data = json.load(file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Expected behavior**
The program should continue to its initial interface. You may find the code in question at `time_management/ddl.py`

**Comment by YBSker** [comment]
Would it be possible for me to take a look at this issue?

**Comment by ancbro** [comment]
> Would it be possible for me to take a look at this issue?

Absolutely @YBSker. Please reach out with questions or comments. Thanks for your interest.

**Comment by YBSker** [comment]
That's great, thanks! I'll try to get started tomorrow or the day after and let you know if I have any questions.

**Comment by YBSker** [comment]
@ancbro I think I handled it so that list_schemas will only read JSON from /table-schemas but I'm having issues publishing my branch...I think i might not have access to write. Apologies if I'm being dumb, I'm a little new at contributing to open-source.

**Comment by ancbro** [comment]
@YBSker No need to apologize; version control is a challenging subject and you never stop learning (trust me). My guess is (and this is totally my fault for not producing better documentation) that you may have cloned the repository without first forking it. If you try and push a branch directly to this repo you will be unable to do so. Take a look at [Fork a repo](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) and then [Create a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). These articles should help guide you in the right direction. I would be happy to help with any issues, related or otherwise, you encounter.

**Comment by YBSker** [comment]
@ancbro  created a pull request. Thank you for the help and advice!

**Comment by ancbro** [comment]
My pleasure. Classy solution. I like it. Merged.
