### ISSUE TITLE
Improve the readme file

### ISSUE THREAD

**Issue by artorias111** [ancbro/time-management#69]
Hey! could the readme file be improved to show how to use the tool, and possibly a few examples?
I can take this up if you'd like.
Cheers.

**Comment by ancbro** [comment]
@artorias111 - apologies for not seeing this sooner. You are welcome to contribute to the `README`, or let me know what you'd like to see, and I can pick up the issue as well. Let me know. Thanks!

**Comment by ancbro** [comment]
@artorias111 I will assign this issue to you, but feel free to let me know if the moment has passed.

**Comment by artorias111** [comment]
Hey! No problem at all, I would love to work on it.

**Comment by ancbro** [comment]
@artorias111 No pressure whatsoever. Are you still interested in tackling this issue? Thanks!

**Comment by artorias111** [comment]
Hey! I'm really sorry I was caught up with a lot of work this past couple of weeks, I'll get started with this soon and let you know if I have any queries! Cheers

**Comment by ancbro** [comment]
> Hey! I'm really sorry I was caught up with a lot of work this past couple of weeks, I'll get started with this soon and let you know if I have any queries! Cheers

@artorias111; No need to apologize. Take as much time as you want. I just wanted to make sure you are still interested. Timeline is totally up to you.

**Comment by artorias111** [comment]
Hey! I added a few things in the readme file of my fork, let me know if this is how you want it, or if you had something else in mind!
 
https://github.com/artorias111/time-management

**Comment by cernoit** [comment]
newbie here. Want to do something useful. I have cloned this but not sure what needs doing?

**Comment by ancbro** [comment]
> Hey! I added a few things in the readme file of my fork, let me know if this is how you want it, or if you had something else in mind!
> 
> https://github.com/artorias111/time-management

Hey @artorias111. Looks good to me. Open up a PR when you're ready and I can approve it. Thanks!

**Comment by ancbro** [comment]
> newbie here. Want to do something useful. I have cloned this but not sure what needs doing?

@cernoit; this ticket is spoken for but I am about to add some more. Feel free to snag any that come up. Thanks.

**Comment by artorias111** [comment]
@ancbro, made a pr, let me know if you want any changes to the readme file!

**Comment by ancbro** [comment]
Thx @artorias111. I merged the PR. Your were the 100th commit! A milestone!

**Comment by artorias111** [comment]
That's great!
