### ISSUE TITLE
Completing a Task should create a Note

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#70]
**Is your feature request related to a problem? Please describe.**
Completing a `Task` should create a `Note`. 

If you complete a `Task` on Monday, there will be no reference of completing that `Task` in Tuesday's `SCRUM` notes. Please add a `Note` for each `Task` that is completed. 

**Describe the solution you'd like**
_When_:
The following user interaction occurs:

1. Run program
2. Select option `1` _Time Management_
3. Select option `5` _Complete tasks_
4. Enter task ID

_Then_:
`def __complete_task(self, first_run=True):` 

_Should_:
Add a `Note` about the action taken. 

`def complete_task(self, row_id):` may need to leverage `def insert_note(self, note):` to accomplish this ticket.

**Comment by angelinjohn** [comment]
I would like to take this up

**Comment by ancbro** [comment]
@angelinjohn Sounds like a plan. I'll be around if you have questions. Thx.

**Comment by sksDonni** [comment]
I am also working on the issue. It would be great if @ancbro  could kindly tell me about the format of the note to be added.

**Comment by angelinjohn** [comment]
https://github.com/ancbro/time-management/pull/71

**Comment by ancbro** [comment]
@angelinjohn Thanks. LGTM. I'll merge this.

**Comment by ancbro** [comment]
@sksDonni I'll open up some new issues soon. If you're interested I'll give you first pick. Thx.
