### ISSUE TITLE
Task Completion Handling

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#73]
**Describe the bug**
The application currently allows a user to complete the same task more than once.

**To Reproduce**
1. Assume a `TASK` with `ID` 1 has been created
2. Select Option 5 to `Complete tasks`
3. Complete the task: `Enter space delimited task IDs for completion: 1`
4. Select Option 4 `Print tasks`
5. Note `TASK: 1    [Date set: 2020-10-21 18:21:55, Days to complete: 1, Completed: true , ...`
6.  Select Option 5 to `Complete tasks`
7. Complete the task: `Enter space delimited task IDs for completion: 1`

**Expected behavior**
If a task is already completed it should not be available to complete again, because _Task Completion_ is no longer idempotent. Every time a task is completed a `NOTE ` is added that the `TASK` has been accomplished. The above code produces the following output when Option 3 `Print notes` is selected.

```
NOTE: 1    [Date set: 2020-10-21 18:23:25] Completed Task 1: Stub
NOTE: 2    [Date set: 2020-10-21 18:29:34] Completed Task 1: Stub
```
Please introduce exception handling that prevents a user from completing the same task more than once. 

Thank you!

**Comment by sksDonni** [comment]
I would like to take this up

**Comment by ancbro** [comment]
@sksDonni  It's all yours. Thanks!
