### ISSUE TITLE
Apply Function Mapping to Maintenance Interface

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#78]
**Is your feature request related to a problem? Please describe.**
`time_management/interface_maintenance.py` should leverage a map data structure to associate user choices with the functions that perform the requested behavior. Currently there exists a `map_choice_to_function(self, choice)` method which uses a conditional control structure to look up and invoke a function corresponding to the given input. This approach is inconsistent with other modules in the project. 

**Describe the solution you'd like**

1. Create a dictionary data structure mapping user inputs to the functions given in the menu. E.g., 
```
 self.__menu_map = {
    "0": interface_common.to_previous_menu,
    "1": self.__foo,
    "2": self.__bar,
}
```
2. Pass the user choice and menu map (dictionary) to `interface_common.map_choice_to_function(self.__menu_map, choice)` inside of `run_menu_loop_tm(self):`
3. Remove unused `map_choice_to_function` code.
4. Format the code using Black. See `CONTRIBUTING.md` for further information.

**Additional context**
The menu map consists of function objects that may (or may not) require partial application. You may use `functools.partial()` to accomplish this. 

Examples of:
1.what the complete listing should look like and
2. how to leverage partial function application 
are given in `time_management/interface_time_management.py`, where this strategy of mapping user inputs to functions already is being used.

**Comment by NickolaiBeloguzov** [comment]
Can I take this?

**Comment by ancbro** [comment]
> Can I take this?

@NickolaiBeloguzov; all yours. Thanks!
