### ISSUE TITLE
Allow Task Voiding

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#80]
**Is your feature request related to a problem? Please describe.**
The `tasks` table schema has a column for voiding a task, but users have no way to do so, even though the `Print Tasks` option clearly displays the field.

`TASK: 1    [Date set: 2020-11-08 10:58:45, Days to complete: 2, Completed: false, Date complete: TBD****************, Void: false] Create story to void task`

**Describe the solution you'd like**
Please create a function in `time_management/facade_tasks.py` that can be invoked to set the void state of a task from `false` to `true`. This story does NOT include adding this method to `time_management/interface_time_management.py` to avoid potential merge conflicts arising from existing stories that will touch the same code.

**Additional context**
You will need to leverage `self.db`, the `SQLiteDatabase` object to execute a query against the `tasks` table. `complete_task(self, row_id)` is a good method to use as a guide.

**Comment by YBSker** [comment]
Hey could I take a look at this issue? Bit of a busy week for me, but I should be able to start looking this weekend at the latest.

**Comment by YBSker** [comment]
Hey, @ancbro I wrote the function and a test case. Apologies for the delay and lack of communication, some last minute things sprung up on me. Would you prefer this function JUST set void to true? Or should it be setting void to the opposite of what it is in the db?

**Comment by ancbro** [comment]
@YBSker; sorry for the slow response. It looks like someone opened up a PR without picking up the ticket. Do you wanna check it out and tell me what you think? This is still your ticket so I am gonna leave it up to you. Could be a good opportunity for some code review and collaboration? https://github.com/ancbro/time-management/pull/91

**Comment by ancbro** [comment]
@YBSker; apologies. I am gonna merge the available PR for this issue in order to get the board cleaned up. Apologies - hope I'm not stepping on your toes too much here. Thank you as always. If you have any follow up tickets or code tweaks you would like to make for this issue or similar ones please do.
