### ISSUE TITLE
days of completion : does not support/handle  empty/string

### ISSUE THREAD

**Issue by akashbilgi** [ancbro/time-management#90]
**Describe the bug**
1) on adding an empty task(**days of completion**)(which is allowed) , when you try to restart the application, it crashes
same happens if **string** is entered.

error log:
  File "C:\Users\<me>\Documents\time-management\time_management\kronos.py", line 61, in is_overdue
    completion_goal = float(completion_goal)
ValueError: could not convert string to float: ''

**To Reproduce**
1. Go to '1. time management'
2. Go to '2.set a task'
3. keep Set a task: <empty>, hit enter
4. keep Days to complete <empty>, hit enter 
5. go to '8.Quit'
6. Try to restart the main.py

**Expected behavior**
empty task/completion days should not be allowed

**Desktop (please complete the following information):**
 - OS: windows

**Comment by NickolaiBeloguzov** [comment]
Assign me please.

**Comment by ancbro** [comment]
@akashbilgi; thanks. @NickolaiBeloguzov; assigned.
